### ISSUE TITLE
the username is used for the password field when reading from config file

### ISSUE THREAD

**Issue by nospam2000** [industrial-edge/pingpong-c#2]
There is probably a copy&paste error in https://github.com/industrial-edge/pingpong-c/blob/main/src/paho_pingpong.c#L255:

instead of 
`password = json_object_get_string(j_username);`

it should probably be 
`password = json_object_get_string(j_password);`

**Comment by HummelN7872** [comment]
Thanks for the hint, we will check and fix it

**Comment by EvaKaul** [comment]
fixed typo in source code
