### ISSUE TITLE
Bug Report: Dangling pointers in paho_pingpong.c

### ISSUE THREAD

**Issue by Rexelpitlum** [industrial-edge/pingpong-c#9]
## Summary

The char pointer assignments at below code location are only valid between the braces of the if branch.

After leaving this scope (when they are actual being used..) the addresses these pointers point to no longer belong to valid data items.

These is true for the `address` pointer, because the char string it points to has only been temporarily put onto the stack, but probably also for the other char pointers (`username`, `password`, `topic1`, `topic2`), as the strings they point to are managed by json objects that have only existed within the scope of the if branch.

## Line of code

https://github.com/industrial-edge/pingpong-c/blob/d74ee7f5603252c6bb3cb2a769d81db2c7c673f2/src/paho_pingpong.c#L253-L259

**Comment by HummelN7872** [comment]
Fixed with latest Pull request
